#! /bin/bash
SOURCE_DIR=$(cd `dirname $0`; pwd)
CMAKE_BUILD_DIR=${SOURCE_DIR}/build
XCODE_PROJECT_NAME=PrincekinOS.xcodeproj
XCODE_PROJECT_PATH=${CMAKE_BUILD_DIR}/${XCODE_PROJECT_NAME}
XCODE_KERNEL_ELF_SCHEME_NAME=kernel.elf
XCODE_XCSCHEMEMANAGEMENT_PLIST_NAME=xcschememanagement.plist
XCODE_XCSCHEMEMANAGEMENT_PLIST_PATH=${XCODE_PROJECT_PATH}/xcuserdata/*.xcuserdatad/xcschemes/${XCODE_XCSCHEMEMANAGEMENT_PLIST_NAME}
CMAKE_GENERATOR="Xcode"
CMAKE_BUILD_TYPE="Debug"
CMAKE_DEBUG_OUTPUT=${SOURCE_DIR}/
CMAKE_RUNTIME_OUTPUT=${SOURCE_DIR}/

mkdir -p ${CMAKE_BUILD_DIR}
cd ${CMAKE_BUILD_DIR}

cmake -G ${CMAKE_GENERATOR} \
	-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG=${CMAKE_DEBUG_OUTPUT} \
    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${CMAKE_RUNTIME_OUTPUT} \
    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO=${CMAKE_RUNTIME_OUTPUT} \
    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=${CMAKE_RUNTIME_OUTPUT} \
    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL=${CMAKE_RUNTIME_OUTPUT} \
    -DCMAKE_BUILD_TYPE=Debug \
    ${SOURCE_DIR}
cd ../
cmake ./
# 执行对 xcschememanagement.plist 的处理，将 target kernel.elf 隐藏

perl -0777 -i.original -pe 's/(<key>kernel.elf.xcscheme_\^#shared#\^_<\/key>[^ key]*<dict>)/\1\n\t\t\t<key>isShown<\/key>\n\t\t\t<false\/>/sg' ${XCODE_XCSCHEMEMANAGEMENT_PLIST_PATH}
